# Use an ARM64 ubuntu base image
FROM debian AS builder

# Avoid interaction during package installation
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/KhronosGroup/OpenCL-Headers.git opencl_headers

RUN cp -r opencl_headers/* /usr/local/include

# Install build essential tools and OpenCL headers
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    ocl-icd-libopencl1 \
    ocl-icd-dev \
    opencl-headers \
    vim \
    ocl-icd-opencl-dev \
    pocl-opencl-icd \
    strace \
    automake bison flex git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN ls
RUN git clone https://github.com/btardio/ecea5307btardio-thrift.git thrift

RUN cd /app/thrift && ./bootstrap.sh
RUN cd /app/thrift && ./configure --disable-debug --disable-dependency-tracking --without-java --without-kotlin --without-python --without-py3 --without-ruby --without-haxe --without-netstd --without-perl --without-php --without-php_extension --without-dart --without-erlang --without-go --without-d --without-nodejs --without-nodets --without-lua --without-rs --without-swift
RUN cd /app/thrift && make -j$(nproc)
RUN cd /app/thrift && make install
RUN cd /app/thrift && make -j$(nproc) -C lib/cpp

COPY ecea5307btardio-thrift/tutorial/tutorial.thrift /app/thrift/tutorial/tutorial.thrift
COPY ecea5307btardio-thrift/tutorial/cpp/CppClient.cpp /app/thrift/tutorial/cpp/CppClient.cpp
COPY ecea5307btardio-thrift/tutorial/cpp/CppServer.cpp /app/thrift/tutorial/cpp/CppServer.cpp
COPY ecea5307btardio-thrift/tutorial/cpp/Makefile.am /app/thrift/tutorial/cpp/Makefile.am

RUN cd /app/thrift && make -j$(nproc)
RUN cd /app/thrift && make install                  
RUN cd /app/thrift && make -j$(nproc) -C lib/cpp

COPY . .

RUN gcc opencl_device.cpp -I/usr/local/include -lOpenCL -o opencl_device

CMD ["/bin/bash"]

FROM debian
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    ocl-icd-libopencl1 \
    pocl-opencl-icd \
    strace \
    python3-pil \
    python3-numpy \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/thrift/tutorial/cpp/.libs/ /.libs
COPY --from=builder /app/thrift/tutorial/cpp/TutorialServer /TutorialServer
COPY --from=builder /app/thrift/tutorial/cpp/TutorialClient /TutorialClient
COPY --from=builder /usr/local/lib/libthrift* /usr/local/lib/


ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"

COPY untitled.png /untitled.png

COPY image_to_rgba.py /image_to_rgba.py
COPY rgba_to_image.py /rgba_to_image.py

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
